### PR TITLE
VersionDetector._autodetect: prioritize the directory name over the f…

### PR DESCRIPTION
**Pull request by aplanas**
…ile name

### CODE REVIEW

**Comment by aplanas** [comment]
IMHO the directory version have more priority over the filename version, because is usually used to access the directory in the %prep section. Also is breaking openstack-gnocchi.

**Comment by toabctl** [comment]
+1

**Comment by aplanas** [comment]
@adrianschroeter can you review this?

**Comment by dirkmueller** [comment]
Makes sense to me..

**Pull request merged**
