### PR TITLE
Disable py26, enable py{33,34} for tests

### PR DESCRIPTION
**Pull request by toabctl**

### CODE REVIEW

**Comment by toabctl** [comment]
@adrianschroeter So my plan is to rewrite ```set_version``` in python. I want to integrate https://github.com/openSUSE/obs-service-set_version_pysemver into this so there is just one ```set_version``` service. Would you accept a rewrite?
And if yes, is python2.6 still needed? Or is OBS running on a platform with python >= 2.7?

**Comment by adrianschroeter** [comment]
rewrite is fine. 
Python 2.6 would be nice to have, since it is still the default in SLE 11.

However, most workstations are using something newer and also the service server has a newer environment.

So, if the code quality would be much better (because no dirty tricks are needed or code can be dropped) we can ignore 2.6

**Comment by toabctl** [comment]
> So, if the code quality would be much better (because no dirty tricks are needed or code can be dropped) we can ignore 2.6

So let's ignore py26 and merge this. Code is simpler in that case.

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
