### PR TITLE
Pysemversion

### PR DESCRIPTION
**Pull request by toabctl**

### CODE REVIEW

**Comment by toabctl** [comment]
Tested with the `openstack-heat` package. Successfully build the package with OBS after converting the .spec file.
@dirkmueller : do you have some time for a review?

**Comment by adrianschroeter** [comment]
hm, big changes ... I will merge and builda new package for openSUSE:Tools. But I won't deploy it right now ...

**Comment by adrianschroeter** [comment]
done, it is tagged as 0.5.0 now

**Comment by toabctl** [comment]
@adrianschroeter thanks! one missing this in the packaging part on OBS is the new `Requires` on `python-packaging`. See https://build.opensuse.org/request/show/318367

**Pull request merged**
