### PR TITLE
enforce files to be decoded as UTF-8

### PR DESCRIPTION
**Pull request by M0ses**
fixes buildtime problems with utf-8 characters, already tested in containers - should work either. No need of locales in container

### CODE REVIEW

**Comment by M0ses** [comment]
For what purpose?

* Works on my machine?
* Works in travis? 
* Works at buildtime in OBS-kvm environment?
* Works inside service containers in OBS?

* Works on my machine - tested while development!
* Works in travis - useless, as nobody runs it travis for production and travis did not save us the last 
  time!
* Works at buildtime - tested while development!
 * Broken anyway ATM 
* Works in containers in OBS -we have checks in place to test the productive env, once we deployed - we check again.

Don`t get me wrong, I love testing - if it`s worth the effort! But in such a complex scenario, I prefer testing the production environment against know problems and invest my time therfore.

**Comment by toabctl** [comment]
> Works in travis - useless, as nobody runs it travis for production and travis did not save us the last
> time!

I don't get that. What do you mean with ```nobody runs it travis for productio``` ? And where did it not save us?

**Comment by M0ses** [comment]
Travis is nice for testing - but it does not reflect our productive environment - passing travis is useless if production breaks.

Where it not saved us? Here:

https://github.com/openSUSE/obs-service-set_version/commit/b2bbe4efb4b4db45e21200eaa76b1c528fd62979

Worked fine in Travis but once deployed, it broke 100% of the service runs, because IIRC glibc-locale was / is / will not be installed in the service containers.

That said -I added a test case for the test suite. 
If there is a 10% chance to find a problem in one of the distributions we support in openSUSE:Tools, I hope it will be worth the effort.

The test does not fail on my machine - neither before nor after my changes. But I tested my changes in productive environment - and there it does make a difference.

**Comment by M0ses** [comment]
Additional note about the travis tests:

All theses tests went fine in travis, but if I run the tests with python3.6 on my laptop 

(CPE_NAME="cpe:/o:opensuse:tumbleweed:20171129")

I get the attached result (and hope on your help to get it fixed). 

This is another reason, why I think, testing in travis (Ubuntu 14.04) is absolutly useless for our productive environment - we should test against our own environment(s).
I implemented production tests for the service containers.
Tests for the buildtime environments are not so easy to implement, as each result strongly depends on the env (e.g. SLE12:GA vs Tumbleweed) and we have not so much resources to test everything.
But if you have any suggestions, how to improve our (productive) testing, I`m really happy to hear about. 

Results on TW:

###############################################################################
XXX@fs-x270:~/prj/obs-service-set_version> python3.6 -m unittest discover tests/ 
................ssssssssssssssssssss........FFFE.................................................
======================================================================
ERROR: test_version_ordering_1____1_1_post10_localver_1____1_1_post10____1_1_post10_dev10____1_1_local1____1_1____1_1rc10_post10____1_1rc10_post10_dev10____1_1rc9____1_1b10_post10____1_1b10_post10_dev10____1_1b10____1_1a10_post10____1_1a10_post10_dev10____1_1a10____1_1_dev10________ (test_python_pip2rpm.VersionCompareTests)
version order should be same between pip and zypper
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ddt.py", line 139, in wrapper
    return func(self, *args, **kwargs)
  File "/home/frank/prj/obs-service-set_version/tests/test_python_pip2rpm.py", line 274, in test_version_ordering
    self._do_version_compare(version_chain[i], op, version_chain[i+1])
  File "/home/frank/prj/obs-service-set_version/tests/test_python_pip2rpm.py", line 153, in _do_version_compare
    "%s: %s > %s" % (type_, vv1, vv2))
  File "/usr/lib64/python3.6/unittest/case.py", line 1218, in assertGreater
    if not a > b:
TypeError: '>' not supported between instances of 'ZypperVersionCompare' and 'ZypperVersionCompare'

======================================================================
FAIL: test_version_normalization_1____1_1a____1_1_a____1_1_a____1_1_a____1_1A____1_1_A____1_1_A____1_1_A____1_1a0____1_1_a0____1_1_a0____1_1_a0____1_1A0____1_1_A0____1_1_A0____1_1_A0____1_1alpha____1_1_alpha____1_1_alpha____1_1_alpha____1_1ALPHA____1_1_ALPHA____1_1_ALPHA____1_1_ALPHA____1_1alpha0____1_1_alpha0____1_1_alpha0____1_1_alpha0____1_1ALPHA0____1_1_ALPHA0____1_1_ALPHA0____1_1_ALPHA0___________1_1a0__ (test_python_pip2rpm.VersionCompareTests)
test packaging's version normalization. There are crazy thinks
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ddt.py", line 139, in wrapper
    return func(self, *args, **kwargs)
  File "/home/frank/prj/obs-service-set_version/tests/test_python_pip2rpm.py", line 235, in test_version_normalization
    "%s%s%s" % (v2, p, d))
  File "/home/frank/prj/obs-service-set_version/tests/test_python_pip2rpm.py", line 150, in _do_version_compare
    "%s: %s == %s" % (type_, vv1, vv2))
AssertionError: 1.1~xalpha0 != 1.1~xalpha0 : zypper: 1.1~xalpha0 == 1.1~xalpha0

======================================================================
FAIL: test_version_normalization_2____1_1b____1_1_b____1_1_b____1_1_b____1_1B____1_1_B____1_1_B____1_1_B____1_1b0____1_1_b0____1_1_b0____1_1_b0____1_1B0____1_1_B0____1_1_B0____1_1_B0____1_1beta____1_1_beta____1_1_beta____1_1_beta____1_1BETA____1_1_BETA____1_1_BETA____1_1_BETA____1_1beta0____1_1_beta0____1_1_beta0____1_1_beta0____1_1BETA0____1_1_BETA0____1_1_BETA0____1_1_BETA0___________1_1b0__ (test_python_pip2rpm.VersionCompareTests)
test packaging's version normalization. There are crazy thinks
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ddt.py", line 139, in wrapper
    return func(self, *args, **kwargs)
  File "/home/frank/prj/obs-service-set_version/tests/test_python_pip2rpm.py", line 235, in test_version_normalization
    "%s%s%s" % (v2, p, d))
  File "/home/frank/prj/obs-service-set_version/tests/test_python_pip2rpm.py", line 150, in _do_version_compare
    "%s: %s == %s" % (type_, vv1, vv2))
AssertionError: 1.1~xbeta0 != 1.1~xbeta0 : zypper: 1.1~xbeta0 == 1.1~xbeta0

======================================================================
FAIL: test_version_normalization_3____1_1c____1_1_c____1_1_c____1_1_c____1_1C____1_1_C____1_1_C____1_1_C____1_1c0____1_1_c0____1_1_c0____1_1_c0____1_1C0____1_1_C0____1_1_C0____1_1_C0____1_1rc____1_1_rc____1_1_rc____1_1_rc____1_1RC____1_1_RC____1_1_RC____1_1_RC____1_1rc0____1_1_rc0____1_1_rc0____1_1_rc0____1_1RC0____1_1_RC0____1_1_RC0____1_1_RC0____1_1pre____1_1_pre____1_1_pre____1_1_pre____1_1PRE____1_1_PRE____1_1_PRE____1_1_PRE____1_1pre0____1_1_pre0____1_1_pre0____1_1_pre0____1_1PRE0____1_1_PRE0____1_1_PRE0____1_1_PRE0____1_1preview____1_1_preview____1_1_preview____1_1_preview____1_1PREVIEW____1_1_PREVIEW____1_1_PREVIEW____1_1_PREVIEW____1_1preview0____1_1_preview0____1_1_preview0____1_1_preview0____1_1PREVIEW0____1_1_PREVIEW0____1_1_PREVIEW0____1_1_PREVIEW0___________1_1rc0__ (test_python_pip2rpm.VersionCompareTests)
test packaging's version normalization. There are crazy thinks
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ddt.py", line 139, in wrapper
    return func(self, *args, **kwargs)
  File "/home/frank/prj/obs-service-set_version/tests/test_python_pip2rpm.py", line 235, in test_version_normalization
    "%s%s%s" % (v2, p, d))
  File "/home/frank/prj/obs-service-set_version/tests/test_python_pip2rpm.py", line 150, in _do_version_compare
    "%s: %s == %s" % (type_, vv1, vv2))
AssertionError: 1.1~xrc0 != 1.1~xrc0 : zypper: 1.1~xrc0 == 1.1~xrc0

----------------------------------------------------------------------
Ran 97 tests in 1.932s

FAILED (failures=3, errors=1, skipped=20)
XXX@fs-x270:~/prj/obs-service-set_version>

**Comment by toabctl** [comment]
> I get the attached result (and hope on your help to get it fixed).

Fixed with https://github.com/openSUSE/obs-service-set_version/pull/52 . The problem why Travis is not detecting this is that ```zypper``` is not installed in travis. That's why some of the tests are not executed.

**Comment by M0ses** [comment]
@toabctl THX for fixing

**Pull request merged**
